# Generated by Django 4.0.5 on 2022-09-24 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aprender', '0002_word_set_folder_user_favoritefolders_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='description',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='set',
            name='chosenWords',
            field=models.ManyToManyField(blank=True, related_name='chosenWords', to='aprender.word'),
        ),
    ]
