# Generated by Django 4.0.5 on 2022-09-25 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aprender', '0003_set_description_alter_set_chosenwords'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
