# Generated by Django 4.0.5 on 2022-09-25 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aprender', '0004_folder_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favoriteFolders',
            field=models.ManyToManyField(null=True, to='aprender.folder'),
        ),
        migrations.AlterField(
            model_name='user',
            name='favoriteSets',
            field=models.ManyToManyField(null=True, to='aprender.set'),
        ),
    ]
