# Generated by Django 4.0.5 on 2022-09-25 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aprender', '0005_alter_user_favoritefolders_alter_user_favoritesets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favoriteFolders',
            field=models.ManyToManyField(blank=True, to='aprender.folder'),
        ),
        migrations.AlterField(
            model_name='user',
            name='favoriteSets',
            field=models.ManyToManyField(blank=True, to='aprender.set'),
        ),
    ]
