# Generated by Django 4.0.5 on 2022-09-25 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aprender', '0006_alter_user_favoritefolders_alter_user_favoritesets'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnWords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('intermediateKnown', models.ManyToManyField(null=True, related_name='intermediateKnown', to='aprender.word')),
                ('lastWord', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lastKnown', to='aprender.word')),
                ('poorKnown', models.ManyToManyField(null=True, related_name='poorKnown', to='aprender.word')),
                ('wellKnown', models.ManyToManyField(null=True, related_name='wellKnown', to='aprender.word')),
            ],
        ),
    ]
