# Generated by Django 4.0.5 on 2022-09-25 16:51

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('aprender', '0007_learnwords'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnwords',
            name='set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.expressions.Case, to='aprender.set'),
        ),
    ]
