# Generated by Django 4.0.5 on 2022-09-25 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aprender', '0008_learnwords_set'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LearnWords',
            new_name='LearnWay',
        ),
    ]
