# Generated by Django 4.0.5 on 2022-09-27 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aprender', '0009_rename_learnwords_learnway'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learnway',
            name='intermediateKnown',
            field=models.ManyToManyField(blank=True, null=True, related_name='intermediateKnown', to='aprender.word'),
        ),
        migrations.AlterField(
            model_name='learnway',
            name='lastWord',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lastKnown', to='aprender.word'),
        ),
        migrations.AlterField(
            model_name='learnway',
            name='poorKnown',
            field=models.ManyToManyField(blank=True, null=True, related_name='poorKnown', to='aprender.word'),
        ),
        migrations.AlterField(
            model_name='learnway',
            name='wellKnown',
            field=models.ManyToManyField(blank=True, null=True, related_name='wellKnown', to='aprender.word'),
        ),
        migrations.AlterField(
            model_name='set',
            name='description',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
