# Generated by Django 4.0.5 on 2022-09-30 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aprender', '0010_alter_learnway_intermediateknown_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learnway',
            name='wellKnown',
        ),
    ]
