# Generated by Django 4.0.5 on 2022-09-30 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aprender', '0011_remove_learnway_wellknown'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnway',
            name='wellKnown',
            field=models.ManyToManyField(blank=True, null=True, related_name='wellKnown', to='aprender.word'),
        ),
    ]
