# Generated by Django 4.0.5 on 2022-10-05 11:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aprender', '0012_learnway_wellknown'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='recentSets',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), default=list, size=None),
        ),
    ]
