# Generated by Django 4.0.5 on 2022-10-05 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aprender', '0012_learnway_wellknown'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='recentSets',
            field=models.CharField(max_length=64),
        ),
    ]
