# Generated by Django 4.0.5 on 2022-10-05 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aprender', '0013_user_recentsets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='recentSets',
            field=models.CharField(max_length=64),
        ),
    ]
