# Generated by Django 4.0.5 on 2022-10-14 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aprender', '0015_remove_user_recentsets_user_recentsetsjson'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profilePic',
            field=models.CharField(default='icons/user.png', max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='recentSetsJson',
            field=models.CharField(default='[]', max_length=64),
        ),
    ]
