# Generated by Django 4.0.5 on 2022-10-14 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aprender', '0016_user_profilepic_alter_user_recentsetsjson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profilePic',
            field=models.ImageField(blank=True, null=True, upload_to='icons/'),
        ),
    ]
