# Generated by Django 4.0.5 on 2022-10-14 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aprender', '0017_alter_user_profilepic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='profilePic',
            new_name='profile_image',
        ),
    ]
