# Generated by Django 4.0.5 on 2022-10-17 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aprender', '0024_alter_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='set_image',
            field=models.ImageField(blank=True, null=True, upload_to='set/'),
        ),
    ]
