# Generated by Django 4.0.5 on 2022-10-19 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aprender', '0025_alter_set_set_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnway',
            name='notStarred',
            field=models.ManyToManyField(blank=True, null=True, related_name='notStarred', to='aprender.word'),
        ),
        migrations.AlterField(
            model_name='set',
            name='chosenWords',
            field=models.ManyToManyField(blank=True, null=True, related_name='chosenWords', to='aprender.word'),
        ),
    ]
