# Generated by Django 4.0.5 on 2022-10-22 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aprender', '0026_learnway_notstarred_alter_set_chosenwords'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
