# Generated by Django 4.0.5 on 2022-10-25 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aprender', '0028_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learnway',
            name='set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aprender.set'),
        ),
    ]
