# Generated by Django 4.0.5 on 2022-10-25 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aprender', '0029_alter_learnway_set'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='images/user.png', upload_to='images/'),
        ),
    ]
